scoremaster Presentation/Controllers/EventController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using scoremaster_Presentation.Data;
using scoremaster_Presentation.Models;
using scoremaster_Presentation.ViewModel;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Security.Claims;
 // For ASP.NET MVC
// or using Microsoft.AspNetCore.Mvc; // For ASP.NET Core
using PdfSharp.Pdf;
using PdfSharp.Drawing;
using System;
using System.IO;

namespace scoremaster_Presentation.Controllers
{
    public class EventController : Controller
    {
        
        private readonly ScoreMasterDbContext _context;
        
        public EventController(ScoreMasterDbContext context)
        {
            _context = context;


        }
        [Authorize(Policy = "Event.List")]
        public IActionResult EventList()
        {
            var user = User.FindFirst(ClaimTypes.Sid)?.Value;
            int uIdint = Convert.ToInt32(user);
            var emp = _context.UsersRegistrations.Where(x => x.UsersRegistrationId == uIdint).FirstOrDefault();
            
            var Event =_context.Event.Where(x=>x.DepartmentId==emp.DepartmentId).ToList();
            return View(Event);
            }
        [Authorize(Policy = "Event.Eventactive")]
        public async Task< IActionResult> Eventactive(int id)
        {
            var Event = _context.Event.Where(x => x.EventId== id && x.IsActive==true).FirstOrDefault();
            Event.IsActive = false;
            _context.Event.Attach(Event);
            _context.Entry(Event).State = EntityState.Modified;
          
            var group = _context.Groups.Where(x => x.EventId == id).ToList();
            foreach (var item in group)
            {
                item.IsActive = false;
                _context.Groups.Attach(item);
                _context.Entry(item).State = EntityState.Modified;
              await  _context.SaveChangesAsync();
            }
          await  _context.SaveChangesAsync();
            return RedirectToAction("EventList");
        }
        [Authorize(Policy = "Event.EventInactive")]
        public async Task< IActionResult> EventInactive(int id)
        {
            var Event = _context.Event.Where(x => x.EventId == id && x.IsActive == false).FirstOrDefault();
            Event.IsActive = true;
            _context.Event.Attach(Event);
            _context.Entry(Event).State = EntityState.Modified;
          
            var group=_context.Groups.Where(x=>x.EventId== id && x.IsActive==false).ToList();
            foreach (var item in group)
            {
                item.IsActive = true;
                _context.Groups.Attach(item);
                _context.Entry(item).State = EntityState.Modified;
               await _context.SaveChangesAsync();
            }

          await  _context.SaveChangesAsync();
            return RedirectToAction("EventList");
        }
     [Authorize(Policy = "Event.Create")]
        [HttpGet]
        public IActionResult EventCreate()

        {
            var user = User.FindFirst(ClaimTypes.Sid)?.Value;
            int uIdint = Convert.ToInt32(user);
            var emp = _context.UsersRegistrations.Where(x => x.UsersRegistrationId == uIdint).FirstOrDefault();

            ViewBag.DeptList = _context.Departments.Where(x=>x.DepartmentId== emp.DepartmentId).ToList();
            ViewBag.Rubrics = _context.RubricCreates.ToList();

            Event Even = new Event();
            return View(Even);
          
        }
        
        [HttpPost]
        public IActionResult EventCreate(Event Events)

        {
            Events.EventDate = DateTime.Now;

            _context.Event.Add(Events);
            _context.SaveChanges();
            return RedirectToAction(nameof(EventList));
        }
 [Authorize(Policy = "Event.Join")]
        [HttpGet]
    
        public IActionResult JoinEvent(int Id)
        {
            var user = User.FindFirst(ClaimTypes.Sid)?.Value;
            int uIdint = Convert.ToInt32(user);
            var empolyee =_context.UsersRegistrations.Where(x=>x.UsersRegistrationId == uIdint).FirstOrDefault();
            var Groups = _context.Groups.Where(x=>x.UsersRegistrationId== empolyee.UsersRegistrationId && x.IsActive==true).ToList();
            return View(Groups );

           
        }
        [Authorize(Policy = "Event.ExamianerJoinEvent")]
        [HttpGet]
        public IActionResult ExamianerJoinEvent(int Id)
        {
            var user = User.FindFirst(ClaimTypes.Sid)?.Value;
            int uIdint = Convert.ToInt32(user);
            var exam = _context.ExternalUserscs.Where(x => x.ExternalUserscsId == uIdint).FirstOrDefault();

            var Groups = _context.Groups.Where(x=>x.EventId== exam.EventId).ToList();
            return View(Groups);


        }
        [Authorize(Policy = "Event.ExamianerMembermarking")]
        public async Task< IActionResult> ExamianerMembermarking(int Id)
        {
            var user = User.FindFirst(ClaimTypes.Sid)?.Value;
            int uIdint = Convert.ToInt32(user);
            var exam = _context.ExternalUserscs.Where(x => x.ExternalUserscsId == uIdint).FirstOrDefault();

            
            ViewBag.UserId = exam?.ExternalUserscsId;
            ViewBag.id = Id;

            RubricDesignVm Vm = new RubricDesignVm();
            Vm.Group = _context.Groups.Where(x => x.GroupId == Id).FirstOrDefault();
            Vm.Members = _context.MemberDatas.Where(x => x.GroupId == Id).ToList();
            var event1 = _context.Event.Where(x => x.EventId == Vm.Group.EventId).FirstOrDefault();
            ViewBag.eventid = event1.EventId;
            ViewBag.markslist = _context.Marks.Where(X => X.EventId == event1.EventId && X.ExternalUserscsId == exam.ExternalUserscsId).ToList();
            ViewBag.rubriclevel =await (from a in _context.RubricCreates
                                        join b in _context.ProgramlearingOutcomes on a.RubricCreateId equals b.RubricCreateId into Programlearing
                                        from Programlearings in Programlearing.DefaultIfEmpty()
                                        join c in _context.EvaluationCriteria on Programlearings.ProgramlearingOutcomesId equals c.ProgramlearingOutcomesId into EvaluationCriteria
                                        from EvaluationCriterias in EvaluationCriteria.DefaultIfEmpty()
                                        join d in _context.EvaluationLevels on EvaluationCriterias.EvaluationCriteriaId equals d.EvaluationCriteriaId into EvaluationLevel
                                        from EvaluationLevels in EvaluationLevel.DefaultIfEmpty()
                                        where a.RubricCreateId == exam.RubricCreateId
                                        select new RubricDesignVm
                                        {
                                            PlO = Programlearings.Name,
                                            PloDescription = EvaluationCriterias.Name,
                                            PloMarks = Convert.ToInt32(EvaluationCriterias.TotalMarks),
                                            PLOType = EvaluationCriterias.Type,
                                            poor = EvaluationLevels.Poor,
                                            BelowAverage = EvaluationLevels.BelowAverae,
                                            AboveAverage = EvaluationLevels.AboveAverae,
                                            Excellent = EvaluationLevels.Excellent,
                                            EvaluationLevelId = EvaluationLevels.EvaluationLevelId
                                        }).Distinct().ToListAsync();
            return View(Vm);


        }
        [HttpPost]
        public async Task<IActionResult> ExamianerMembermarking(RubricDesignVm vm, int Groupid)
        {
            int evlid = 0;
            Marks marks = new Marks();
            foreach (var item in vm.Marks)
            {
                marks.EvaluationLevels = await _context.EvaluationLevels.FindAsync(item.EvaluationLevelId);
                evlid = marks.EvaluationLevels.EvaluationLevelId;
                if (item.TotalMarks != null)
                {
                    var member = _context.Marks.Where(x => x.MemberDataId == item.MemberDataId && x.ExternalUserscsId== item.ExternalUserscsId && x.EvaluationLevels.EvaluationLevelId == item.EvaluationLevelId && x.EventId == item.EventId).FirstOrDefault();
                    if (member != null)
                    {
                        member.TotalMarks = item.TotalMarks;
                        _context.Marks.Attach(member);
                        _context.Entry(member).State = EntityState.Modified;
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        marks.MarksId = 0;
                        marks.TotalMarks = item.TotalMarks;
                        marks.EventId = item.EventId;
                        marks.ExternalUserscsId = item.ExternalUserscsId;
                        marks.MemberDataId = item.MemberDataId;
                        marks.EvaluationLevelId = evlid;
                        _context.Marks.Add(marks);
                        await _context.SaveChangesAsync();
                    }

                }
            }
            return RedirectToAction("ExamianerMembermarking", new { Id = Groupid });
        }
      //  [Authorize(Policy = "Event.EventResult")]
        [HttpGet]
        public async Task<IActionResult> EventResult(int id)
        {
           

            var marks = await (
        from a in _context.Marks
        join d in _context.MemberDatas on a.MemberDataId equals d.MemberDataId into MemberMarks
        from Member in MemberMarks.DefaultIfEmpty()
            where a.EventId == id
      //  group new { Member, a } by new { a.MemberDataId, a.TotalMarks } into grouped
        select new
        {

scoremaster Presentation/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using scoremaster_Presentation.Data;
using scoremaster_Presentation.Migrations;
using scoremaster_Presentation.ViewModel;
using scoremaster_Presentation.Models;
using System;
using Microsoft.AspNetCore.Authorization;

namespace scoremaster_Presentation.Controllers
{
    public class RoleController : Controller
    {
        private readonly ScoreMasterDbContext _context;
        public RoleController(ScoreMasterDbContext context)
        {
            _context = context;


        }
        [Authorize(Policy = "Roles")]
        [HttpGet]
        public async Task<IActionResult> Roles()
        {
            RolesVM roleVM = new RolesVM();
            var roles = await _context.Roles.Where(x => x.IsActive == true).ToListAsync();
            roleVM.roles = roles.Select(x => new RolesList { RoleId = x.ROleId, RoleName = x.RoleName, IsActive = (bool)x.IsActive }).Where(x => x.IsActive == true).ToList();
            foreach (var role in roleVM.roles)
            {
                var permissions = from a in _context.UserPermisions
                                  from b in _context.Permissions
                                  where a.RoleId == role.RoleId && b.PermissionId == a.PermissionId
                                  select new
                                  {
                                      PermissionName = b.PesmissionName
                                  };
                List<string> permiss = new List<string>();
                role.Permission = permissions.Select(x => x.PermissionName).ToList();
            }
            return View(roleVM);
        }

        [Authorize(Policy = "AddRole")]
        [HttpGet]
        public async Task< IActionResult> AddRole()
        {

            RolesVM roles = new RolesVM();
            roles.AddUpdatePermissions = await _context.Permissions.Where(x => x.IsActive == true).Select(x => new scoremaster_Presentation.ViewModel.Permission { PermissionId = x.PermissionId, PermissionName = x.PesmissionName }).ToListAsync();
            return View(roles);
        }
        [HttpPost]
        public async Task<IActionResult> AddRoles(RolesVM role)
        {

           Roles? Rolen = new Roles();
            Rolen.RoleName= role.RoleName.ToLower();
            await _context.Roles.AddAsync(Rolen);
             _context.SaveChanges();

            var recentRole = await _context.Roles.OrderBy(x => x.ROleId).LastOrDefaultAsync();
                var selectedPermissions = role.AddUpdatePermissions.Where(x => x.isSelected == true).ToList();
            foreach (var permission in selectedPermissions)
            {
                var rolePermissions = new UserPermision();

                rolePermissions.RoleId = recentRole.ROleId;
                rolePermissions.PermissionId = permission.PermissionId;

                await _context.UserPermisions.AddAsync(rolePermissions);
                _context.SaveChanges();
            }



            return RedirectToAction(nameof(Roles));
        }


        [Authorize(Policy = "UpdateRole")]
        [HttpGet]
        public async Task<IActionResult> UpdateRole(int id)
        {
            var temp = await _context.Roles.Where(x => x.ROleId == id).FirstOrDefaultAsync();
            var user = new RolesVM
            {
                RoleId = temp.ROleId,
                //IsActive = (bool)temp.IsActive,
                //RoleName = temp.RollName
            };
            user.AddUpdatePermissions = await _context.Permissions.Select(x => new scoremaster_Presentation.ViewModel.Permission { PermissionId = x.PermissionId, PermissionName = x.PesmissionName }).ToListAsync();
            var userPermissions = await _context.UserPermisions.Where(x => x.RoleId == id).ToListAsync();
            foreach (var rolep in user.AddUpdatePermissions)
            {
                foreach (var permission in userPermissions)
                {
                    if (rolep.PermissionId == permission.PermissionId)
                    {
                        rolep.isSelected = true;
                    }
                }
            }
            return View(user);
        }
       
        [HttpPost]
        public async Task<IActionResult> UpdateRole(RolesVM role)
        {
            var temp = await _context.Roles.Where(x => x.ROleId == role.RoleId).FirstOrDefaultAsync();
            if (temp != null)
            {
                var oldPermissions = await _context.UserPermisions.Where(x => x.RoleId == temp.ROleId).ToListAsync();
                _context.UserPermisions.RemoveRange(oldPermissions);
                await _context.SaveChangesAsync();

                var newPermissions = role.AddUpdatePermissions.Where(x => x.isSelected).Select(p => new UserPermision
                {
                    RoleId = temp.ROleId,
                    PermissionId = p.PermissionId
                }).ToList();

                await _context.UserPermisions.AddRangeAsync(newPermissions);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Roles));
        }

    }
}

scoremaster Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - scoremaster_Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/scoremaster_Presentation.styles.css" asp-append-version="true" />



    @* Focus template *@
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="~/css/focus/lib/calendar2/pignose.calendar.min.css" rel="stylesheet" />
    <link href="~/css/focus/lib/chartist/chartist.min.css" rel="stylesheet" />
    <link href="~/css/focus/lib/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/focus/lib/themify-icons.css" rel="stylesheet" />
    <link href="~/css/focus/lib/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/css/focus/lib/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/css/focus/lib/weather-icons.css" rel="stylesheet" />
    <link href="~/css/focus/lib/menubar/sidebar.css" rel="stylesheet" />
    <link href="~/css/focus/lib/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/focus/lib/helper.css" rel="stylesheet" />
    <link href="~/css/focus/style.css" rel="stylesheet" />
    <link href="~/css/focus/lib/data-table/buttons.bootstrap.min.css" rel="stylesheet" />


    <link href="~/css/focus/default.css" rel="stylesheet" />
    <link href="~/css/focus/component.css" rel="stylesheet" />
   
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures">
        <div class="nano">
            <div class="nano-content">
                <ul>
                    <div class="logo">
                        <a asp-controller="Home" asp-action="Index">
                            <!-- <img src="images/logo.png" alt="" /> --><span>ScoreMaster</span>
                        </a>
                    </div>
                    @if (User.HasClaim("Permission", "ExternalUser") || User.HasClaim("Permission", "Users") || User.HasClaim("Permission", "UserRegisterCreate") || User.HasClaim("Permission", "Changepassword"))
                    {
                        <li class="label">Main</li>
                        <li>
                            <a class="sidebar-sub-toggle">
                                <i class="ti-home"></i> Users <span class="badge badge-primary">2</span> <span class="sidebar-collapse-icon ti-angle-down"></span>
                            </a>
                            <ul>
                                @if (User.HasClaim("Permission", "ExternalUser"))
                                {
                                    <li><a class="nav-menu-item" asp-controller="ExternelUser" asp-action="ExternalUser"><i class="ti-user"></i>Examiner</a></li>
                                }
                                @if (User.HasClaim("Permission", "Users"))
                                {
                                    <li><a class="nav-menu-item" asp-controller="Registration" asp-action="Users"><i class="ti-user"></i>Empolyee List</a> </li>

                                }

                                @if (User.HasClaim("Permission", "UserRegisterCreate"))
                                {
                                    <li> <a asp-controller="Registration" asp-action="UserRegisterCreate" class="nav-menu-item"><i class="ti-user"></i>Add Empolyee</a></li>
                                }
                                @if (User.HasClaim("Permission", "Changepassword"))
                                {
                                <li> <a asp-controller="Registration" asp-action="UserChangePassword" class="nav-menu-item"><i class="ti-user"></i>Change Password</a></li>
                                }
                                </ul>
                        </li>
                    }
                    @if (User.HasClaim("Permission", "Department.List") || User.HasClaim("Permission", "Department.Create"))
                    {
                    <li class="label">Department</li>
                    <li>
                        <a class="sidebar-sub-toggle">
                            <i class="ti-bar-chart-alt"></i> Department <span class="sidebar-collapse-icon ti-angle-down"></span>
                        </a>
                        <ul>
                            <li><a class="nav-menu-item" asp-controller="Department" asp-action="DepartmentList"><i class="ti-user"></i>Department</a>
                            <li><a class="nav-menu-item" asp-controller="Department" asp-action="AddDepartment"><i class="ti-user"></i>AddDepartment</a>
                        </ul>
                    </li>
                    }
                    @if (User.HasClaim("Permission", "Event.List") || User.HasClaim("Permission", "Event.Create") || User.HasClaim("Permission", "Event.Join"))
                            {
                    <li class="label">Event</li>
                    <li>
                        <a class="sidebar-sub-toggle">
                            <i class="ti-target"></i> Event<span class="sidebar-collapse-icon ti-angle-down"></span>
                        </a>
                        <ul>
                           
                            @if (User.HasClaim("Permission", "Event.List"))
                            {
                                  <li><a class="nav-menu-item" asp-controller="Event" asp-action="EventList"><i class="ti-user"></i>Events</a></li>
                           }
                            @if (User.HasClaim("Permission", "Event.Create"))
                            {

                                <li><a class="nav-menu-item" asp-controller="Event" asp-action="EventCreate"><i class="ti-user"></i>Event Create</a></li>
                            }
                            @if (User.HasClaim("Permission", "Event.Join"))
                            {
                            <li><a class="nav-menu-item" asp-controller="Event" asp-action="JoinEvent"><i class="ti-user"></i> Join Event</a></li>
                            }
                        </ul>
                    </li>
                    }
                     @if (User.HasClaim("Permission", "Event.ExamianerJoinEvent"))
                            {
                    <li class="label"> Examiner Join Event</li>
                    <li>
                        <a class="sidebar-sub-toggle">
                            <i class="ti-target"></i> Event<span class="sidebar-collapse-icon ti-angle-down"></span>
                        </a>
                        <ul>

                            
                           
                                <li><a class="nav-menu-item" asp-controller="Event" asp-action="ExamianerJoinEvent"><i class="ti-user"></i> Join Event</a></li>
                           
                        </ul>
                    </li>
                    }
                    @if (User.HasClaim("Permission", "Rubrics") || User.HasClaim("Permission", "RubricsCreate"))
                    {
                        <li class="label">Rubrics</li>
                        <li>
                            <a class="sidebar-sub-toggle">
                                <i class="ti-target"></i>Rubrics<span class="sidebar-collapse-icon ti-angle-down"></span>
                            </a>
                            <ul>


                                <li><a class="nav-menu-item" asp-controller="Rubrics" asp-action="Rubrics"><i class="ti-user"></i>Rubrics</a></li>



                                <li><a class="nav-menu-item" asp-controller="Rubrics" asp-action="RubricsCreate"><i class="ti-user"></i>Create Rubrics</a></li>


                            </ul>
                        </li>
                    }

                    @if (User.HasClaim("Permission", "Roles") || User.HasClaim("Permission", "UpdateRole") || User.HasClaim("Permission", "AddRole"))
                    {

                        <li class="label">Role</li>
                        <li>
                            <a class="sidebar-sub-toggle">
                                <i class="ti-target"></i> Role<span class="sidebar-collapse-icon ti-angle-down"></span>
                            </a>
                            <ul>
                                <li><a class="nav-menu-item" asp-controller="Role" asp-action="AddRole"><i class="ti-user"></i>Create Role</a>
                                    <li>
                                        <a class="nav-menu-item" asp-controller="Role" asp-action="Roles"><i class="ti-user"></i>Roles</a>

                            </ul>
                        </li>
                    }
                    <li><a class="nav-menu-item" asp-controller="Login" asp-action="LoginPage"><i class="ti-close"></i> Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /# sidebar -->

    <div class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="hamburger sidebar-toggle">
                            <span class="line"></span>
                            <span class="line"></span>
                            <span class="line"></span>
                        </div>
                    </div>
                    <div class="float-right">
                        <p>Developed by M. Ismail & Naseeb Ullah </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-wrap">
        <div class="main">
            @RenderBody()
        </div>
    </div>
   
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)



   @*  Focus template *@

    <script src="~/js/focus/lib/bootstrap.min.js"></script>
    <script src="~/js/focus/lib/jquery.nanoscroller.min.js"></script>
    <script src="~/js/focus/lib/menubar/sidebar.js"></script>
    <script src="~/js/focus/lib/preloader/pace.min.js"></script>
    <script src="~/js/focus/lib/bootstrap.min.js"></script>
   <script src="~/js/focus/scripts.js"></script>
  
    <!-- bootstrap -->
    <script src="~/js/focus/lib/calendar-2/moment.latest.min.js"></script>
    <script src="~/js/focus/lib/calendar-2/pignose.calendar.min.js"></script>
    <script src="~/js/focus/lib/calendar-2/pignose.init.js"></script>
    <script src="~/js/focus/lib/weather/jquery.simpleweather.min.js"></script>

    <script src="~/js/focus/lib/weather/weather-init.js"></script>
    <script src="~/js/focus/lib/circle-progress/circle-progress.min.js"></script>

    <script src="~/js/focus/lib/circle-progress/circle-progress-init.js"></script>
    <script src="~/js/focus/lib/chartist/chartist.min.js"></script>
    <script src="~/js/focus/lib/sparklinechart/jquery.sparkline.min.js"></script>
    <script src="~/js/focus/lib/sparklinechart/sparkline.init.js"></script>
    <script src="~/js/focus/lib/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/js/focus/lib/owl-carousel/owl.carousel-init.js"></script>
    
    <script src="~/js/focus/lib/data-table/datatables.min.js"></script>
    <script src="~/js/focus/lib/data-table/dataTables.buttons.min.js"></script>
    <script src="~/js/focus/lib/data-table/buttons.flash.min.js"></script>
    <script src="~/js/focus/lib/data-table/jszip.min.js"></script>
    <script src="~/js/focus/lib/data-table/pdfmake.min.js"></script>
    <script src="~/js/focus/lib/data-table/vfs_fonts.js"></script>
    <script src="~/js/focus/lib/data-table/buttons.html5.min.js"></script>
    <script src="~/js/focus/lib/data-table/buttons.print.min.js"></script>
    <script src="~/js/focus/lib/data-table/datatables-init.js"></script>
 
    <!-- scripit init-->
    <script src="js/dashboard2.js"></script>
    @* datatable *@ 
    
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
</body>
</html>